import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {GoogleOAuthProvider} from "@react-oauth/google"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <GoogleOAuthProvider clientId="765927338968-ssitlq4nqal70s8mfp31vpbm0t568laf.apps.googleusercontent.com">
        {children}
      </GoogleOAuthProvider>
      </body>
    </html>
  );
}
